version: "3"
services:
    #react app container
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
        
